/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define STM32F411xE
#include "stm32f4xx.h"

#define PA5 5
#define PC13 13

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 * Варіант 7 (23)
 *
 * Організувати миготіння PA5 з частотою 50 Гц, тривалість імпульсу 10 мс, змінювати
 * частоту на 25 Гц при натисканні кнопки PC13
 */


void Delay(volatile uint32_t iterations) {
    while(iterations--) {
        __NOP(); // Keeps the timing stable and prevents optimization
    }
}

// wrapper for ms
void delay_ms(uint32_t ms) {
    for (uint32_t i = 0; i < ms; i++) {
        Delay(2000); // 2000 iterations = 1ms at 16MHz
    }
}

int main(void) {
    // 1. Enable clocks for Port A
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;

    // 2. Configure PA5 as output, green LED
    GPIOA->MODER &= ~(3 << (PA5 * 2)); // clear bits
    GPIOA->MODER |=  (1 << (PA5 * 2)); // set to 01, output mode

    // 3. Configure PC13 as input
    GPIOA->MODER &= ~(3 << (PC13 * 2));  // 00 (Input)
    uint8_t use_25Hz = 0;
    while (1) {
    	// Check if button is pressed (Active LOW)
		if (!(GPIOC->IDR & (1 << PC13))) {
			delay_ms(20); // Debounce delay
			if (!(GPIOC->IDR & (1 << PC13))) {
				use_25Hz = !use_25Hz; // Toggle the mode
				// Wait for button release so it doesn't toggle repeatedly
				while (!(GPIOC->IDR & (1 << PC13)));
			}
		}

		//LED BLINKING
		GPIOA->BSRR = (1 << PA5); // Turn ON
		delay_ms(10);                 // Pulse is always 10ms

		GPIOA->BSRR = (1 << (PA5 + 16)); // Turn OFF

		if (use_25Hz) {
			// 25 Hz = 40ms period -> 10ms ON / 30ms OFF
			delay_ms(30);
		} else {
			// 50 Hz = 20ms period -> 10ms ON / 10ms OFF
			delay_ms(10);
		}
	}
}
